import time
import queue

from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.tools import tool
from rai.agents.langchain import create_react_runnable

from rai.communication.ros2 import (
    ROS2Context,
    ROS2Connector,
    ROS2HRIConnector,
    wait_for_ros2_topics,
)

from rai_whoami.models import EmbodimentInfo

import rai.tools.ros2.navigation.nav2 as nav2_module

from rai.tools.ros2.navigation.nav2 import (
    NavigateToPoseTool,
    GetNavigateToPoseResultTool,
)

from action_msgs.msg import GoalStatus

from rai_s2s.asr import SpeechRecognitionAgent

import logging

logging.basicConfig(
    format="[RAI] %(asctime)s %(name)s[%(process)d] %(levelname)s %(message)s",
    force=True,
)


@ROS2Context()
def main():
    
    # ros2 connector
    ros2_connector = ROS2Connector()

    # interaction mode
    print("\nSelect interaction mode:")
    print("1 - Text")
    print("2 - Voice")

    while True:
        choice = input("> ").strip()

        if choice == "1":
            interaction_mode = "text"
            print("Text mode enabled.\n")
            break

        if choice == "2":
            interaction_mode = "voice"
            print("Voice mode enabled.\n")
            break

        print("Please enter 1 or 2.")


    # voice input
    voice_queue = queue.Queue()

    hri_connector = None
    speech_agent = None


    if interaction_mode == "voice":

        def on_human_message(message):
            """
            Callback executed when SpeechRecognitionAgent publishes
            a transcription on /from_human.
            """

            text = message.text.strip()

            if text:
                voice_queue.put(text)


        # Listen to the transcriptions generated by the ASR system.
        hri_connector = ROS2HRIConnector()

        hri_connector.register_callback(
            source="/from_human",
            callback=on_human_message,
        )


        # Start the same ASR system that was previously run
        # as a separate Python program.
        speech_agent = SpeechRecognitionAgent.from_config(
            "config.toml"
        )

        speech_agent.run()


    def get_voice_input() -> str:
        """
        Wait until the next vocal message has been transcribed.
        """

        print("[VOICE] Listening...")

        text = voice_queue.get()

        return text.strip()

    def get_user_input(prompt: str = "> ") -> str:
        """
        Get input either from the keyboard or from speech,
        depending on the selected interaction mode.
        """

        if interaction_mode == "voice":
            return get_voice_input()

        return input(prompt)


    wait_for_ros2_topics(
        ros2_connector,
        [
            "/amcl_pose",
            "/initialpose",
        ],
    )


    navigate_to_pose = NavigateToPoseTool(
        connector=ros2_connector
    )

    get_navigate_result = GetNavigateToPoseResultTool(
        connector=ros2_connector
    )

    # navigate to coordinate
    @tool
    def navigate_to_location(
        x: float,
        y: float,
        yaw: float = 0.0,
    ) -> str:
        """
        Navigate the TIAGo robot to a target pose in the map frame
        and wait until the navigation action finishes.

        x and y are in meters.
        yaw is in radians.
        """

        # Reset state from any previous navigation.
        nav2_module.current_result = None
        nav2_module.current_feedback = None

        # Start navigation.
        start_result = navigate_to_pose.invoke({
            "x": x,
            "y": y,
            "z": 0.0,
            "yaw": yaw,
        })

        print(f"[NAVIGATION] {start_result}", flush=True)

        # Wait for this navigation action to finish.
        while True:
            result = get_navigate_result.invoke({})

            if result != "Action is not done yet":
                action_response = nav2_module.current_result.result()
                status = action_response.status

                if status == GoalStatus.STATUS_SUCCEEDED:
                    print(f"[NAVIGATION] SUCCESS: reached x={x}, y={y}", flush=True)
                    return (
                        f"Navigation SUCCEEDED. "
                        f"Robot reached target x={x}, y={y}, yaw={yaw}."
                    )

                elif status == GoalStatus.STATUS_ABORTED:
                    print(f"[NAVIGATION] FAILED: navigation ABORTED to x={x}, y={y}", flush=True)
                    return (
                        f"Navigation ABORTED. "
                        f"Robot did not reach target x={x}, y={y}, yaw={yaw}."
                    )

                elif status == GoalStatus.STATUS_CANCELED:
                    print(f"[NAVIGATION] FAILED: navigation CANCELED to x={x}, y={y}", flush=True)
                    return (
                        f"Navigation CANCELED. "
                        f"Robot did not reach target x={x}, y={y}, yaw={yaw}."
                    )

                else:
                    print(
                        f"[NAVIGATION] FAILED: unexpected status {status} "
                        f"for x={x}, y={y}"
                    )
                    return (
                        f"Navigation finished with unexpected action status "
                        f"{status}. Target was x={x}, y={y}, yaw={yaw}."
                    )

            time.sleep(0.5) # check if the navigation is finished at 2 Hz
    
    # navigate to semantic locations
    @tool
    def navigate_to_named_location(location: str) -> str:
        """
        Navigate TIAGo to a known semantic location and wait until navigation
        finishes.

        Use this tool whenever the user asks the robot to go to a named room,
        door, corridor, or open space.

        Available locations:
        - open_space
        - door_entrance_1
        - door_entrance_2
        - corridor_1
        - room_1
        - room_2
        - room_3
        - room_4
        - room_5
        - room_6
        - room_7
        """

        locations = {
            "open_space": (0.0, 0.0, 0.0),
            "door_entrance_1": (5.50, 10.5, 0.0),
            "door_entrance_2": (-3.30, 8.0, 0.0),
            "corridor_1": (1.56, 5.03, 0.0),
            "room_1": (7.5, 7.5, 0.0),
            "room_2": (4.87, 7.33, 0.0),
            "room_3": (-3.12, 6.51, 0.0),
            "room_4": (-6.12, -7.74, 0.0),
            "room_5": (-0.96, -6.82, 0.0),
            "room_6": (4.36, -5.94, 0.0),
            "room_7": (9.85, -6.25, 0.0),
        }

        location = location.lower().strip()

        if location not in locations:
            return (
                f"Unknown location '{location}'. "
                f"Available locations: {', '.join(locations.keys())}."
            )

        x, y, yaw = locations[location]

        return navigate_to_location.invoke({
            "x": x,
            "y": y,
            "yaw": yaw,
        })

    # wait tool
    @tool
    def wait_seconds(seconds: float) -> str:
        """
        Keep the robot stationary for the specified number of seconds.
        """

        if seconds < 0:
            return "Waiting time cannot be negative."

        if seconds > 60:
            return "Waiting time cannot exceed 60 seconds."

        time.sleep(seconds)

        return f"Waited for {seconds:.1f} seconds."
    
    # human interaction
    @tool
    def ask_user(question: str) -> str:
        """
        Ask the human a question and wait for their response.

        The tool blocks until the human answers.
        Use the returned answer to decide what action to perform next.
        """

        print(f"\n[TIAGO-AGENT] {question}", flush=True)

        answer = get_user_input("[USER] ").strip()

        print(f"{answer}", flush=True)

        return answer

    # agent tools
    custom_tools = [
        navigate_to_location,
        navigate_to_named_location,
        ask_user,
        wait_seconds,
    ]

    # embodiment
    embodiment_info = EmbodimentInfo.from_file("tiago_embodiment.json")

    sys_prompt = embodiment_info.to_langchain()
    
    # create agent
    agent = create_react_runnable(
        tools=custom_tools,
        system_prompt=sys_prompt,
    )

    # conversation
    state = {'messages': []}
    print("LangChain/LangGraph Agent (Local Setup) for TIAGo simulation is ready.")


    # main loop
    try:
        while True:
            input_text = get_user_input("[USER] ").strip()
            
            print(f"{input_text}", flush=True)

            state["messages"].append(HumanMessage(content=input_text))
            response = agent.invoke(state)
            state["messages"] = response["messages"]

            reply = ""

            for m in reversed(response["messages"]):
                if isinstance(m, AIMessage) and getattr(m, "content", None):
                    reply = m.content
                    break
            
            print(f"\n[TIAGO-AGENT]: {reply}" if reply else "\n[TIAGO-AGENT]: [Tools executed, no final text reply]", flush=True)
    
    except KeyboardInterrupt:
        print("\nStopping TIAGo agent...")

    finally:
        # Stop the asr system only if voice mode was used.
        if speech_agent is not None:
            speech_agent.stop()

        if hri_connector is not None:
            hri_connector.shutdown()


if __name__ == "__main__":
    main()
